### ISSUE TITLE
brew install not working with current code

### ISSUE THREAD

**Issue by prashanthmadarapu** [gardener/homebrew-tap#11]
**What happened**:
Tried to brew tap and brew install but brew install failed with following error.
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gardenctl"
Download failed: https://github.com/gardener/gardenctl/releases/download/v0.25.0/gardenctl-darwin-amd64
```
**What you expected to happen**:
brew install should be executed successfully and install gardener cli.

**How to reproduce it (as minimally and precisely as possible)**:
- execute following commands
  - brew tap gardener/tap
  - brew install gardenctl

**Anything else we need to know**:
no

**Environment**:
MacOS Catalina

**Comment by neo-liang-sap** [comment]
this is due to our testing with GithubAction with `gardenctl`, i will revert the changes 
/CC @AndreasBurger @dansible @zanetworker
